name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy and build
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd acs/rvendas
            git pull
            npm install
            npm run build
            sudo docker compose down
            sudo sh -c 'docker rmi -f $(docker images -aq)'
            sudo docker build . -t rvendas:$(date +%s)
            sudo docker compose up -d --force-recreate
            sudo docker image prune -f
