name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy and build
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd rvendas
            git pull
            npm run build
            echo ${{secrets.SUDO}} | sudo -S sh -c 'docker rmi -f $(docker images -aq)'
            echo ${{secrets.SUDO}} | sudo -S docker build . -t rvendas:$(date +%s)
            echo ${{secrets.SUDO}} | sudo -S docker compose down
            echo ${{secrets.SUDO}} | sudo -S docker compose up -d --force-recreate
            echo ${{secrets.SUDO}} | sudo -S docker image prune -f
